spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test(You should change the database name to your database)
    username: <mention your database username>
    password: <mention your database password>
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true